name: capstone_dashboard
description: "Flutter admin dashboard UI with Supabase-ready setup."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  supabase_flutter: ^2.6.0
  login_module:
    path: packages/login_module
  rfid_management_module:
    path: packages/rfid_management_module
  virtual_admission_slip:
    path: packages/virtual_admission_slip
  admin_dashboard:
    path: packages/admin_dashboard
  discipline_officer_module:
    path: packages/discipline_officer_module
  guidance_counselor_module:
    path: packages/guidance_counselor_module
  kiosk:
    path: packages/kiosk_home
  student_kiosk_module:
    path: packages/student_kiosk_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
