import 'dart:async' show Timer;
import 'dart:math' show min;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'admission_slip_data.dart';

/// Tailwind-aligned palette (Flutter has no Tailwind runtime; these mirror common tokens).
abstract final class _Tw {
  static const Color pageBg = Color(0xFFF0F4FF); // mint page (screenshot)
  static const Color white = Color(0xFFFFFFFF);
  static const Color gray200 = Color(0xFFE5E7EB);
  static const Color gray500 = Color(0xFF6B7280);
  static const Color gray900 = Color(0xFF111827);
  static const Color red50 = Color(0xFFFEF2F2);
  static const Color rose600 = Color(0xFFE11D48);
  static const Color blue600 = Color(0xFF2563EB);
  static const Color blue900 = Color(0xFF1E3A8A);
  static const Color yellow50 = Color(0xFFFFFBEB);
  static const Color yellow200 = Color(0xFFFDE68A);
  static const Color amber800 = Color(0xFF92400E);
  static const Color amber900 = Color(0xFF78350F);
  static const Color slate300 = Color(0xFFCBD5E1);
}

/// Where [AdmissionSlipPreviewScreen] currently is in its lifecycle.
///
/// [printing]/[printed] are only entered via [AdmissionSlipPreviewScreen]'s
/// "Confirm & Print" action — the plain "Confirm" action still goes
/// straight from [submitting] to [submitted].
enum AdmissionSlipStatus { pending, submitting, submitted, printing, printed, error }

/// Full-screen preview of an admission slip, shown BEFORE anything is
/// written to the database — [data]'s `slipId` (and the QR code built from
/// it) is generated by the host app up front, so it's already valid the
/// instant this screen renders even though the underlying record doesn't
/// exist yet. Nothing is persisted until [onConfirm]/[onConfirmAndPrint]
/// actually succeeds; [onCancel] simply discards everything shown here.
///
/// Replaces the old read-only "AdmissionSlipGeneratedView" (single "Done"
/// button, always post-write) — the class name is kept for this file's
/// history but the type is now `AdmissionSlipPreviewScreen`.
class AdmissionSlipPreviewScreen extends StatefulWidget {
  const AdmissionSlipPreviewScreen({
    super.key,
    this.data = const AdmissionSlipData(),
    required this.onCancel,
    required this.onConfirm,
    required this.onConfirmAndPrint,
    required this.onPrint,
    required this.onDone,
  });

  final AdmissionSlipData data;

  /// Discards the slip — nothing has been written, so this just goes back
  /// one screen (to let the reporter edit their offense selection).
  final VoidCallback onCancel;

  /// Writes the slip + its violations. Throwing surfaces the error message
  /// via this screen's own error state (with a retry path); resolving
  /// normally transitions to the "submitted" state.
  final Future<void> Function() onConfirm;

  /// Same as [onConfirm] — writes the slip + its violations. Distinct from
  /// [onConfirm] only in which terminal state follows a successful write:
  /// this one leads into the [AdmissionSlipStatus.printing] animation and
  /// [onPrint], instead of straight to [AdmissionSlipStatus.submitted].
  final Future<void> Function() onConfirmAndPrint;

  /// Fired once during [AdmissionSlipStatus.printing], concurrently with
  /// the slide-down animation — the host wires this to the actual printer
  /// call (e.g. a silent direct-to-printer call on the kiosk). This screen
  /// doesn't call the app's printing code directly since that lives in the
  /// host app, not this presentation-only package. Never awaited for
  /// failure handling here: whatever this does is expected to handle/log
  /// its own errors internally, since [AdmissionSlipStatus.printed] is
  /// always shown next regardless of whether printing actually succeeded.
  final Future<void> Function() onPrint;

  /// Tapped from the post-submission "Done" state — distinct from
  /// [onCancel] because the right destination is different: Cancel goes
  /// back one screen to edit; Done (after a real write happened) should
  /// return all the way to the kiosk's idle scan screen, ready for the
  /// next person.
  final VoidCallback onDone;

  @override
  State<AdmissionSlipPreviewScreen> createState() =>
      _AdmissionSlipPreviewScreenState();
}

class _AdmissionSlipPreviewScreenState
    extends State<AdmissionSlipPreviewScreen> {
  static const _printAnimationDuration = Duration(milliseconds: 700);
  static const _autoReturnDuration = Duration(seconds: 4);

  AdmissionSlipStatus _status = AdmissionSlipStatus.pending;
  String? _errorMessage;
  Timer? _autoReturnTimer;

  @override
  void dispose() {
    _autoReturnTimer?.cancel();
    super.dispose();
  }

  Future<void> _handle(
    Future<void> Function() action, {
    required bool andPrint,
  }) async {
    setState(() {
      _status = AdmissionSlipStatus.submitting;
      _errorMessage = null;
    });
    try {
      await action();
      if (!mounted) return;
      if (andPrint) {
        await _runPrintSequence();
      } else {
        setState(() => _status = AdmissionSlipStatus.submitted);
      }
    } catch (e) {
      if (!mounted) return;
      setState(() {
        _status = AdmissionSlipStatus.error;
        _errorMessage = '$e';
      });
    }
  }

  /// Plays the slide-down animation and fires [AdmissionSlipPreviewScreen
  /// .onPrint] concurrently, waits for both to finish, then shows the
  /// [AdmissionSlipStatus.printed] success message and auto-returns via
  /// [AdmissionSlipPreviewScreen.onDone] after [_autoReturnDuration] — no
  /// tap needed, since nobody is expected to operate this screen once
  /// printing has started.
  Future<void> _runPrintSequence() async {
    setState(() => _status = AdmissionSlipStatus.printing);
    await Future.wait<void>([
      Future<void>.delayed(_printAnimationDuration),
      // A throwing onPrint is a contract violation (its doc comment says
      // it's expected to handle its own errors) — guarded here anyway so
      // one misbehaving host implementation can't block the slip from
      // reaching "printed", which is meant to show unconditionally once
      // printing has started.
      widget.onPrint().catchError((Object _) {}),
    ]);
    if (!mounted) return;
    setState(() => _status = AdmissionSlipStatus.printed);
    _autoReturnTimer = Timer(_autoReturnDuration, () {
      if (mounted) widget.onDone();
    });
  }

  TextStyle _poppins({
    double fontSize = 14,
    FontWeight fontWeight = FontWeight.w400,
    Color color = _Tw.gray900,
    double? height,
    double letterSpacing = 0,
  }) {
    return GoogleFonts.poppins(
      fontSize: fontSize,
      fontWeight: fontWeight,
      color: color,
      height: height,
      letterSpacing: letterSpacing,
    );
  }

  String get _title => switch (_status) {
        AdmissionSlipStatus.submitted ||
        AdmissionSlipStatus.printing ||
        AdmissionSlipStatus.printed =>
          'Admission Slip Confirmed',
        _ => 'Review Admission Slip',
      };

  String get _subtitle => switch (_status) {
        AdmissionSlipStatus.submitted =>
          'Scan the QR code below to save a copy, or present it to your teacher.',
        AdmissionSlipStatus.printing => 'Printing your admission slip...',
        AdmissionSlipStatus.printed => 'Have a great day!',
        _ => 'Review the details below before confirming.',
      };

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: _Tw.pageBg,
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.fromLTRB(20, 60, 20, 40),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Text(
                _title,
                textAlign: TextAlign.center,
                style: _poppins(fontSize: 22, fontWeight: FontWeight.w700),
              ),
              const SizedBox(height: 8),
              Text(
                _subtitle,
                textAlign: TextAlign.center,
                style: _poppins(fontSize: 13, color: _Tw.gray500),
              ),
              const SizedBox(height: 16),
              Expanded(
                child: LayoutBuilder(
                  builder: (context, constraints) {
                    final cardWidth = min(580.0, constraints.maxWidth);
                    final slidAway = _status == AdmissionSlipStatus.printing ||
                        _status == AdmissionSlipStatus.printed;
                    return Align(
                      alignment: Alignment.topCenter,
                      child: SizedBox(
                        width: cardWidth,
                        child: _status == AdmissionSlipStatus.printed
                            ? _PrintedSuccessView(poppins: _poppins)
                            : SingleChildScrollView(
                                child: AnimatedSlide(
                                  duration: _printAnimationDuration,
                                  curve: Curves.easeInCubic,
                                  offset: slidAway
                                      ? const Offset(0, 1.2)
                                      : Offset.zero,
                                  child: AnimatedOpacity(
                                    duration: _printAnimationDuration,
                                    opacity: slidAway ? 0 : 1,
                                    child: _SlipCard(
                                      data: widget.data,
                                      poppins: _poppins,
                                      showQr: widget.data.qrUrl.isNotEmpty,
                                    ),
                                  ),
                                ),
                              ),
                      ),
                    );
                  },
                ),
              ),
              const SizedBox(height: 16),
              if (_status != AdmissionSlipStatus.printing &&
                  _status != AdmissionSlipStatus.printed)
                LayoutBuilder(
                  builder: (context, constraints) {
                    final actionWidth = min(580.0, constraints.maxWidth);
                    return Align(
                      alignment: Alignment.topCenter,
                      child: SizedBox(
                        width: actionWidth,
                        child: _ActionArea(
                          status: _status,
                          errorMessage: _errorMessage,
                          poppins: _poppins,
                          onCancel: widget.onCancel,
                          onConfirm: () =>
                              _handle(widget.onConfirm, andPrint: false),
                          onConfirmAndPrint: () => _handle(
                            widget.onConfirmAndPrint,
                            andPrint: true,
                          ),
                          onDone: widget.onDone,
                        ),
                      ),
                    );
                  },
                ),
            ],
          ),
        ),
      ),
    );
  }
}

class _ActionArea extends StatelessWidget {
  const _ActionArea({
    required this.status,
    required this.errorMessage,
    required this.poppins,
    required this.onCancel,
    required this.onConfirm,
    required this.onConfirmAndPrint,
    required this.onDone,
  });

  final AdmissionSlipStatus status;
  final String? errorMessage;
  final TextStyle Function({
    double fontSize,
    FontWeight fontWeight,
    Color color,
    double? height,
    double letterSpacing,
  }) poppins;
  final VoidCallback onCancel;
  final VoidCallback onConfirm;
  final VoidCallback onConfirmAndPrint;
  final VoidCallback onDone;

  @override
  Widget build(BuildContext context) {
    if (status == AdmissionSlipStatus.submitted) {
      return FilledButton(
        onPressed: onDone,
        style: FilledButton.styleFrom(
          backgroundColor: _Tw.blue900,
          foregroundColor: _Tw.white,
          padding: const EdgeInsets.symmetric(vertical: 16),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        ),
        child: Text('Done', style: poppins(fontSize: 20, fontWeight: FontWeight.w600, color: _Tw.white)),
      );
    }

    final busy = status == AdmissionSlipStatus.submitting;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        if (status == AdmissionSlipStatus.error && errorMessage != null)
          Container(
            margin: const EdgeInsets.only(bottom: 12),
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: _Tw.red50,
              borderRadius: BorderRadius.circular(10),
            ),
            child: Text(
              errorMessage!,
              style: poppins(fontSize: 12, color: _Tw.rose600, fontWeight: FontWeight.w600),
            ),
          ),
        Row(
          children: [
            Expanded(
              child: OutlinedButton(
                onPressed: busy ? null : onCancel,
                style: OutlinedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 14),
                  side: const BorderSide(color: _Tw.slate300),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                ),
                child: Text('Cancel', style: poppins(fontSize: 15, fontWeight: FontWeight.w600)),
              ),
            ),
          ],
        ),
        const SizedBox(height: 10),
        FilledButton(
          onPressed: busy ? null : onConfirm,
          style: FilledButton.styleFrom(
            backgroundColor: _Tw.blue600,
            foregroundColor: _Tw.white,
            padding: const EdgeInsets.symmetric(vertical: 14),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          ),
          child: busy
              ? const SizedBox(
                  width: 18, height: 18,
                  child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white),
                )
              : Text('Confirm', style: poppins(fontSize: 15, fontWeight: FontWeight.w600, color: _Tw.white)),
        ),
        const SizedBox(height: 10),
        FilledButton.icon(
          onPressed: busy ? null : onConfirmAndPrint,
          icon: const Icon(Icons.print_outlined, size: 18),
          label: Text('Confirm & Print', style: poppins(fontSize: 15, fontWeight: FontWeight.w600, color: _Tw.white)),
          style: FilledButton.styleFrom(
            backgroundColor: _Tw.blue900,
            foregroundColor: _Tw.white,
            padding: const EdgeInsets.symmetric(vertical: 14),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          ),
        ),
      ],
    );
  }
}

/// Shown once [AdmissionSlipStatus.printed] is reached — the slip card has
/// already finished sliding away by this point (see the `AnimatedSlide`
/// wrapper in `build()`), so this appears where the card was.
class _PrintedSuccessView extends StatelessWidget {
  const _PrintedSuccessView({required this.poppins});

  final TextStyle Function({
    double fontSize,
    FontWeight fontWeight,
    Color color,
    double? height,
    double letterSpacing,
  }) poppins;

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          const Icon(
            Icons.check_circle_rounded,
            size: 72,
            color: _Tw.blue600,
          ),
          const SizedBox(height: 16),
          Text(
            'Printed successfully.',
            textAlign: TextAlign.center,
            style: poppins(fontSize: 20, fontWeight: FontWeight.w700),
          ),
          const SizedBox(height: 4),
          Text(
            'Kindly get your printed admission slip.',
            textAlign: TextAlign.center,
            style: poppins(fontSize: 14, color: _Tw.gray500),
          ),
        ],
      ),
    );
  }
}

class _SlipCard extends StatelessWidget {
  const _SlipCard({
    required this.data,
    required this.poppins,
    required this.showQr,
  });

  final AdmissionSlipData data;
  final bool showQr;
  final TextStyle Function({
    double fontSize,
    FontWeight fontWeight,
    Color color,
    double? height,
    double letterSpacing,
  }) poppins;

  @override
  Widget build(BuildContext context) {
    return Material(
      color: _Tw.white,
      elevation: 6,
      shadowColor: Colors.black26,
      borderRadius: BorderRadius.circular(20),
      clipBehavior: Clip.antiAlias,
      child: Padding(
        padding: const EdgeInsets.fromLTRB(22, 22, 22, 20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text(
              'VIRTUAL ADMISSION SLIP',
              textAlign: TextAlign.center,
              style: poppins(fontSize: 17, fontWeight: FontWeight.w700, letterSpacing: 0.2),
            ),
            const SizedBox(height: 4),
            Text(
              'Disciplinary Office',
              textAlign: TextAlign.center,
              style: poppins(fontSize: 13, fontWeight: FontWeight.w500, color: _Tw.gray500),
            ),
            const SizedBox(height: 16),
            const Divider(height: 1, thickness: 1, color: _Tw.gray200),
            const SizedBox(height: 18),
            Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Expanded(
                  child: _FieldColumn(entries: [
                    _Field('Student Name', data.studentName),
                    const SizedBox(height: 14),
                    _Field('Grade & Section', data.gradeSection),
                  ]),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: _FieldColumn(entries: [
                    _Field('Student Number', data.studentNumber),
                    const SizedBox(height: 14),
                    _Field('Slip ID', data.slipId),
                  ]),
                ),
              ],
            ),
            const SizedBox(height: 20),
            Text(
              'Acknowledged Violations:',
              style: poppins(fontSize: 12, fontWeight: FontWeight.w500, color: _Tw.gray500),
            ),
            const SizedBox(height: 8),
            Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
              decoration: BoxDecoration(color: _Tw.red50, borderRadius: BorderRadius.circular(12)),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  Container(
                    padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                    decoration: BoxDecoration(color: _Tw.rose600, borderRadius: BorderRadius.circular(999)),
                    child: Text(
                      data.violationCode,
                      style: poppins(fontSize: 11, fontWeight: FontWeight.w600, color: Colors.white),
                    ),
                  ),
                  const SizedBox(width: 10),
                  Expanded(
                    child: Text(
                      data.violationDescription,
                      style: poppins(fontSize: 13, fontWeight: FontWeight.w600, height: 1.25),
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 18),
            const Divider(height: 1, thickness: 1, color: _Tw.gray200),
            const SizedBox(height: 18),
            _Field('Issue Date & Time', data.issueDateTime),
            const SizedBox(height: 14),
            _Field('Valid Until', data.validUntil),
            const SizedBox(height: 14),
            Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Padding(
                  padding: EdgeInsets.only(top: 2),
                  child: Icon(Icons.schedule, size: 18, color: _Tw.blue600),
                ),
                const SizedBox(width: 6),
                Expanded(
                  child: Text(
                    'Time Remaining: ${data.timeRemaining}',
                    style: poppins(fontSize: 13, fontWeight: FontWeight.w600, color: _Tw.blue600, height: 1.3),
                  ),
                ),
              ],
            ),
            if (showQr) ...[
              const SizedBox(height: 18),
              const Divider(height: 1, thickness: 1, color: _Tw.gray200),
              const SizedBox(height: 18),
              _QrSection(url: data.qrUrl, poppins: poppins),
              const SizedBox(height: 4),
            ],
            const SizedBox(height: 16),
            _ImportantNotice(poppins: poppins),
          ],
        ),
      ),
    );
  }
}

/// Shown to the student (scan to save a copy) and later, by a teacher
/// scanning the same code, to look the slip up — see `lib/main_slip.dart`
/// in the host app for what actually opens.
class _QrSection extends StatelessWidget {
  const _QrSection({required this.url, required this.poppins});

  final String url;
  final TextStyle Function({
    double fontSize,
    FontWeight fontWeight,
    Color color,
    double? height,
    double letterSpacing,
  }) poppins;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            color: _Tw.white,
            border: Border.all(color: _Tw.gray200),
            borderRadius: BorderRadius.circular(12),
          ),
          child: QrImageView(
            data: url,
            size: 140,
            backgroundColor: _Tw.white,
          ),
        ),
        const SizedBox(height: 8),
        Text(
          'Scan to save on your phone, or for a teacher to look up this slip',
          textAlign: TextAlign.center,
          style: poppins(fontSize: 11, color: _Tw.gray500),
        ),
      ],
    );
  }
}

class _ImportantNotice extends StatelessWidget {
  const _ImportantNotice({required this.poppins});

  final TextStyle Function({
    double fontSize,
    FontWeight fontWeight,
    Color color,
    double? height,
    double letterSpacing,
  }) poppins;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: _Tw.yellow50,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: _Tw.yellow200),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(Icons.warning_amber_rounded, color: Colors.amber.shade600, size: 22),
          const SizedBox(width: 10),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Important Notice',
                  style: poppins(fontSize: 14, fontWeight: FontWeight.w700, color: _Tw.amber900),
                ),
                const SizedBox(height: 6),
                Text(
                  'This admission slip is valid for 72 hours only. Present this to your teacher '
                  'before entering class. Any attempt to duplicate or forge this slip will result '
                  'in additional disciplinary action.',
                  style: poppins(fontSize: 12, fontWeight: FontWeight.w500, color: _Tw.amber800, height: 1.45),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _FieldColumn extends StatelessWidget {
  const _FieldColumn({required this.entries});

  final List<Widget> entries;

  @override
  Widget build(BuildContext context) {
    return Column(crossAxisAlignment: CrossAxisAlignment.start, children: entries);
  }
}

class _Field extends StatelessWidget {
  const _Field(this.label, this.value);

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    final base = GoogleFonts.poppins();
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label, style: base.copyWith(fontSize: 12, fontWeight: FontWeight.w500, color: _Tw.gray500)),
        const SizedBox(height: 4),
        Text(value, style: base.copyWith(fontSize: 14, fontWeight: FontWeight.w700, color: _Tw.gray900, height: 1.25)),
      ],
    );
  }
}
