name: rfid_management_module
description: RFID Management dashboard UI for STI Baliuag Capstone.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  camera: ^0.11.0+2
  dashboard_layout:
    path: ../dashboard_layout
  discipline_officer_module:
    path: ../discipline_officer_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
